### ISSUE TITLE
The output is incorrect

### ISSUE THREAD

**Issue by Davider-code** [msftrncs/PwshReadXmlPList#6]
Use the following code to see the value of a key. The output is incorrect

Sample file:
[test.zip](https://github.com/msftrncs/PwshReadXmlPList/files/7140892/test.zip)

```PowerShell
$pList = [xml](get-content "C:\Users\Administrator\Desktop\test.plist") | ConvertFrom-Plist
$pList.ACPI.DSDT.Patches.find
```
_________________________________________________________________________________________________
out:
80
88
83
88
8
95
65
68
82
0
8
95
80
82
87
18
6
2
71
70
88
48
72
68
69
70
95
68
83
77
72
69
67
73

**Comment by msftrncs** [comment]
Hi, @kyjdp.  The output is correct.

`Patches` is an array, and in PowerShell when you reference members within an array without specifying the array index, you get all of them.

There are 13 members in the array:
```PowerShell
$plist.ACPI.DSDT.Patches.Length
```

Try this command, to see them all separately using Format-Hex
```PowerShell
$plist.ACPI.DSDT.Patches.foreach{ $_.Find | Format-Hex }
```
or  reference each one
```PowerShell
$plist.ACPI.DSDT.Patches[0].Find | Format-Hex
$plist.ACPI.DSDT.Patches[1].Find | Format-Hex
# and so on...
```

**Comment by Davider-code** [comment]
> Hi, @kyjdp. The output is correct.
> 
> `Patches` is an array, and in PowerShell when you reference members within an array without specifying the array index, you get all of them.
> 
> There are 13 members in the array:
> 
> ```powershell
> $plist.ACPI.DSDT.Patches.Length
> ```
> 
> Try this command, to see them all separately using Format-Hex
> 
> ```powershell
> $plist.ACPI.DSDT.Patches.foreach{ $_.Find | Format-Hex }
> ```
> 
> or reference each one
> 
> ```powershell
> $plist.ACPI.DSDT.Patches[0].Find | Format-Hex
> $plist.ACPI.DSDT.Patches[1].Find | Format-Hex
> # and so on...
> ```

@msftrncs
Hello, thank you for your reply
Sometimes I need to look at the actual values of these arrays because I want to modify them
Is there a way to fix this problem? Thank you in advance

PS:
In PowerShell programming language, I spent a lot of time looking for functions to modify plist files. Your function is the only and most powerful,
Thank you for your great work

**Comment by msftrncs** [comment]
> Sometimes I need to look at the actual values of these arrays because I want to modify them
> Is there a way to fix this problem? Thank you in advance

There is one thing that complicates these arrays.  When you query the `Find` property without specifying the index to the `Patches` array, the result is an array of an array of bytes and PowerShell will just concatenate them together in to a single array of bytes.   To modify them, you must process each element of the `Patches` array separately, such as using the `.foreach` special method, the `ForEach-Object` special commandlet, the `foreach` statement or lastly creating a `for` loop to iterate the array.  If you need to modify only a single instance, or just a few, you will need to provide a condition to control the modification.

```PowerShell
$plist.ACPI.DSDT.Patches.foreach{ 
    # modify `$_.Find` here
}

# or

$plist.ACPI.DSDT.Patches | ForEach-Object { 
    # modify `$_.Find` here
}

# or

foreach ($patch in $plist.ACPI.DSDT.Patches) {
    # modify `$patch.Find` here
}

# or

for ($i = 0; $i -lt $plist.ACPI.DSDT.Patches.Length; $i ++ ) {
    # modify `$plist.ACPI.DSDT.Patches[$i].Find` here
}
```
