### ISSUE TITLE
Empty elements returned without declared data type, causing incorrect behavior in downstream tools

### ISSUE THREAD

**Issue by Davider-code** [msftrncs/PwshReadXmlPList#7]
Using the following code, a null label will be output incorrectly, 
Sample file
[test.zip](https://github.com/msftrncs/PwshJSONtoPList/files/7143140/test.zip)

before:
```xml
                    <key>Base</key>
                    <string></string>
```                    
after:
```xml
                    		<key>Base</key>
				<dict>
				</dict>
```								
_______________________________________________________________

before:
```xml
                    <key>ReplaceMask</key>
                    <data></data>
```  
after:
```xml
				<key>ReplaceMask</key>
				<dict>
				</dict>
```								
_______________________________________________________________

before:
```xml
            <key>Patch</key>
            <array/>
```
after:
```xml
		<key>Patch</key>
		<dict>
		</dict>
```

powershell code:

```PowerShell
$pList = [xml](get-content "C:\Users\Administrator\Desktop\s1.plist") | ConvertFrom-Plist

$pList | ConvertTo-Plist -Indent "`t" -StateEncodingAs 'UTF-8' -Depth 6 | Set-Content 'C:\Users\Administrator\Desktop\s1-ok.plist' -Encoding 'UTF8'

```

**Comment by msftrncs** [comment]
I've determined that this issue is in [msftrncs/PwshReadXmlPList](https://github.com/msftrncs/PwshReadXmlPList), and it has to do with a failure to handle empty nodes while processing the XML node tree.
